function montage = compi_montage_swap_channels(id)
% ------------------------------------------------------------------------- 
% COMPI_MONTAGE_SWAP_CHANNELS Creates the montage struct for swapping TP7 
% and FT9 channels in the COMPI study.
%   IN:     id          - subject identifier string, e.g. '0001'
%   OUT:    montage     - the montage struct with labels and montage matrix
% ------------------------------------------------------------------------- 

montage = struct;

montage.labelorg = {...
    'Fp1', 'AF7', 'AF3', 'F1', 'F3', 'F5', 'F7', 'FT7', ...
    'FC5', 'FC3', 'FC1', 'C1', 'C3', ...
    'C5', 'T7', 'TP7', 'CP5', 'CP3', 'CP1', 'P1', 'P3', ...
    'P5', 'P7',	'P9',	'PO7', 'PO3', 'O1', 'Iz', 'Oz', ...
    'POz','Pz', 'CPz', 'Fpz', 'Fp2', 'AF8', 'AF4', ...
    'AFz', 'Fz', 'F2', 'F4', 'F6', 'F8', 'FT8', 'FC6', ...
    'FC4', 'FC2', 'FCz', 'Cz', 'C2', 'C4', 'C6', 'T8', ...
    'TP8', 'CP6', 'CP4', 'CP2', 'P2', 'P4', 'P6', 'P8',	...
    'P10', 'PO8', 'PO4', 'O2', 'FT9', 'PO9', 'FT10', ...
    'PO10', 'HeRe',	'HeLi', 'VeUp',	'VeDo', 'EMG1a', ...
    'EMG1b', 'EMG2a', 'EMG2b', 'EMG3a',	'EMG3b',	'EMG4a', ...
    'EMG4b', 'C17', 'C18', 'C19', 'C20',	'C21', 'C22', ...
    'C23', 'C24', 'C25', 'C26',	'C27', 'C28', 'C29', ...
    'C30', 'C31', 'C32', 'EXG1', 'EXG2', 'EXG3', 'EXG4', ...
    'EXG5', 'EXG6', 'EXG7', 'EXG8', 'Status'};

montage.labelnew = montage.labelorg;

tra = eye(105);

switch id
    % swap channels TP7 (16) and FT9 (65)
    case {'0118'}
        tra(16, 16)   = 0;
        tra(16, 65)  = 1;
        tra(65, 65) = 0;
        tra(65, 16)  = 1; 
    otherwise
        disp('No channel swapping');
end

montage.tra = tra;

end